# Generated by Django 6.0.3 on 2026-03-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
